version: '3.5'

services:
  blog_build:
    build: ../
    container_name: 'blog_build'
    volumes:
      - dist:/usr/src/app/dist

  blog_web:
    image: nginx
    ports:
      - 8011:80
    container_name: 'blog_web'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist: